name: Sync Docs as Code - Confluence
on:
  push:
    branches:
      - main
    paths:
      - "*"
      - "!.github/**"
jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    name: Sync Docs as Code - Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find All Markdown Files
        id: find-files
        run: |
          # Get all .md files except those in .github/
          files=$(find . -path "./.github" -prune -o -type f -name "*.md" -print)
          echo "Found files:"
          echo "$files"
          # Format as JSON array for multi-file processing
          echo "files_json=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      - name: Test Confluence API Connection
        run: |
          echo "Testing Confluence API access..."
          RESPONSE=$(curl -s -u "${{ secrets.USERNAME }}:${{ secrets.API_TOKEN }}" \
            "${{ secrets.BASE_URL }}/rest/api/space/${{ secrets.SPACE_KEY }}")
          echo "API Response: $RESPONSE"
          if [[ $RESPONSE == *"\"statusCode\":401"* ]]; then
            echo "ERROR: Unauthorized (check username/api_token)"
            exit 1
          elif [[ $RESPONSE == *"\"statusCode\":404"* ]]; then
            echo "ERROR: Space not found (check space-key)"
            exit 1
          else
            echo "✅ Confluence API access successful!"
          fi
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@v3
        with:
          folder: ${{ steps.find-files.outputs.files_json }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.API_TOKEN }}
          confluence-base-url: ${{ secrets.BASE_URL }}
          space-key: ${{ secrets.SPACE_KEY }}
          parent-page-id: ${{ secrets.PARENT_PAGE_ID }}
